# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
jobs:
  publish-npm-electron_updater_node_cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/electron_updater_node_cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: node ../../script/npm_sync_version.js
        env:
          VERSIONS: ${{ github.ref_name }}
      - run: npm run build
      - run: npm run build:types
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}  
  publish-npm-electron_updater_node_core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/electron_updater_node_core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: node ../../script/npm_sync_version.js
        env:
          VERSIONS: ${{ github.ref_name }}
      - run: npm run build
      - run: npm run build:types
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
