name: test build
on: push
  branches:
  - main

jobs:
  test-cli-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/electron_updater_node_cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: yarn install && npm run build
  test-core-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/electron_updater_node_core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: yarn install && npm run build
